development:
  adapter: postgresql
  encoding: unicode
  database: open_graph_development
  pool: 5
  username: open_graph
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: open_graph_test
  pool: 5
  username: open_graph
  password: password1